server:
  port: ${SERVER_PORT:8080}

spring:
  sql:
    init:
      mode: never

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:pos_local}
    username: ${DB_USERNAME:pos_user}
    password: ${DB_PASSWORD:pos_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: foundation_local
        format_sql: true

  flyway:
    baseline-on-migrate: true
    create-schemas: true
    default-schema: foundation_local
    schemas: foundation_local

security:
  jwt:
    secret: local-dev-secret-key-for-hs256-minimum-32b

app:
  security:
    refresh-token:
      pepper: change-this-local-dev-refresh-token-pepper

  bootstrap:
    super-admin:
      enabled: true
      email: kecidavid22@gmail.com
      username: admin
      password: ChangeMe123!
      first-name: Super
      last-name: Admin
    sample-menus:
      enabled: true

  mail:
    from: no-reply@pos.local

  auth:
    password-reset:
      token-pepper: change-this-local-dev-password-reset-pepper

    email-verification:
      token-pepper: change-this-local-dev-email-verification-pepper

    sms:
      code-pepper: change-this-local-dev-sms-code-pepper
